ecommerce/src/Entity/Admin.php
<?php

namespace App\Entity;

use App\Repository\AdminRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=AdminRepository::class)
 */
class Admin
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=45)
     */
    private $firstname;

    /**
     * @ORM\Column(type="string", length=45)
     */
    private $lastname;

    /**
     * @ORM\Column(type="string", length=45)
     */
    private $email;

    /**
     * @ORM\Column(type="string", length=45)
     */
    private $password;

    /**
     * @ORM\Column(type="datetime_immutable")
     */
    private $created_at;

    /**
     * @ORM\Column(type="datetime_immutable")
     */
    private $updated_at;

    /**
     * @ORM\Column(type="string", length=45, nullable=true)
     */
    private $picture;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFirstname(): ?string
    {
        return $this->firstname;
    }

    public function setFirstname(string $firstname): self
    {
        $this->firstname = $firstname;

        return $this;
    }

    public function getLastname(): ?string
    {
        return $this->lastname;
    }

    public function setLastname(string $lastname): self
    {
        $this->lastname = $lastname;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getPassword(): ?string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeImmutable $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeImmutable
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(\DateTimeImmutable $updated_at): self
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    public function getPicture(): ?string
    {
        return $this->picture;
    }

    public function setPicture(?string $picture): self
    {
        $this->picture = $picture;

        return $this;
    }
}

ecommerce/src/Controller/HomeController.php
<?php

namespace App\Controller;
use App\Entity\Category;
use App\Entity\Client;
use App\Entity\Command;
use App\Entity\CommandProduct;
use App\Entity\Comments;
use App\Entity\History;
use App\Entity\Payment;
use App\Entity\Product;
use App\Entity\User;
use App\Form\CommentsFormType;
use App\Form\CommentsType;
use App\Form\CreateClientFormType;
use App\Form\LivraisonFormType;
use App\Service\Cart\CartService;
use App\Form\SearchProductFormType;
use App\Repository\CommentsRepository;
use App\Repository\ProductRepository;
use App\Service\AppService;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Core\Encoder\UserPasswordEncoderInterface;

class HomeController extends AbstractController
{
     /**
     * @Route("/", name="home")
     */
    public function home( CartService $cartService, Request $request, ProductRepository $productRepository)
    {   
        $user = '';
        $client = null;
        if($this->getUser() && $this->getUser()->getRoles()[0] == "ROLE_USER") {
            $client = $this->getDoctrine()->getRepository(Client::class)->findOneBy(['email' => $this->getUser()->getEmail()]);
            $user = $client->getFirstname() . ' ';
        }
        $categories = $this->getDoctrine()->getRepository(Category::class)->findAll();
        $products = $this->getDoctrine()->getRepository(Product::class)->findAll();
        $search = $request->request->get('search_product');

        if($request->getMethod() == 'POST')
        {
            $products = $productRepository->search($search);
        }
        return $this->render('home/home.html.twig', [
            'categories' => $categories,
            'products' => $products,
            'client' => $client,
            'user' => $user,
            'total' => $cartService->getTotal(),
            'totalItem' => $cartService->getTotalItem(),
        ]);
       
    }

     /**
     * @Route("/details/{id}", name="details")
     */
    public function details(Product $produit, Request $request, $id, CartService $cartService, CommentsRepository $commentsRepository): Response
    {
        $user = '';
        $client = null;

        if($this->getUser() && $this->getUser()->getRoles()[0] == "ROLE_USER") {
            $client = $this->getDoctrine()->getRepository(Client::class)->findOneBy(['email' => $this->getUser()->getEmail()]);
            $user = $client->getFirstname() . ' ';
        }

        try{
            $product = $this->getDoctrine()->getRepository(Product::class)->findOneBy(['id' => $id]);
            $_products = $this->getDoctrine()->getRepository(Product::class)->findBy(['category' => $product->getCategory()]);
            $__products = [];
            $products = [];

            foreach($_products as $_product)
            {
                if($_product->getId() != $id)
                {
                    array_push($__products, $_product);
                }
            }

            $index = array_rand($__products, 3);

            foreach($index as $i)
            {
                array_push($products, $__products[$i]);
            }

            $post = new Comments();
        
            $formulaire = $this->createForm(CommentsFormType::class, $post);
    
            $formulaire->handleRequest($request);
    
            $formulaire->getErrors();
    
            if($formulaire->isSubmitted() && $formulaire->isValid())
            {
                $post->setProduct($product);
                
                $parentId = $formulaire->get("parent")->getData();
        

                $em = $this->getDoctrine()->getManager();

            
                
                if($parentId != null){

                    $parent = $em->getRepository(Comments::class)->find($parentId);
                }

                // On définit le parent
                $post->setParent($parent ?? null);

                $em->persist($post);
                
                $em->flush();
                $this->addFlash('message', 'Votre commentaire a bien été envoyé');
                return $this->redirectToRoute("details", [
                    'id' => $product->getId()    
                ]);
            }
    
           
            $comments = $commentsRepository->findBy(['product' => $produit]);

            return $this->render('home/details.html.twig', [
                'product' => $product,
                'products' => $products,
                'client' => $client,
                'user' => $user,
                'total' => $cartService->getTotal(),
                'totalItem' => $cartService->getTotalItem(),
                'comments' => $comments,
                'formulaire' => $formulaire->createView(),
            ]);
        }
        catch(\Exception $e){
            return $this->render('error.html.twig', [
                'error' => $e->getMessage(),
            ]);
        }
    }

  
    /*======================================================== */
    /**
    * @Route("/forum", name="forum")
    */
    public function forum (CommentsRepository $commentsRepository, CartService $cartService, Request $request, ProductRepository $productRepository)
    {
        $user = '';
        $client = null;
        if($this->getUser() && $this->getUser()->getRoles()[0] == "ROLE_USER") {
            $client = $this->getDoctrine()->getRepository(Client::class)->findOneBy(['email' => $this->getUser()->getEmail()]);
            $user = $client->getFirstname() . ' ';
        }
        $categories = $this->getDoctrine()->getRepository(Category::class)->findAll();
        $products = $this->getDoctrine()->getRepository(Product::class)->findAll();
        $search = $request->request->get('search_product');

        if($request->getMethod() == 'POST')
        {
            $products = $productRepository->search($search);
        }

        $posts = $commentsRepository->findAll();

        $post = new Comments();
        
        $formulaire = $this->createForm(CommentsFormType::class, $post);

        $formulaire->handleRequest($request);
        $formulaire->getErrors();
        if($formulaire->isSubmitted() && $formulaire->isValid())
        {   
            $parentId = $formulaire->get("parent")->getData();
        

            $em = $this->getDoctrine()->getManager();

           
            
            if($parentId != null){

                $parent = $em->getRepository(Comments::class)->find($parentId);
            }

            // On définit le parent
            $post->setParent($parent ?? null);

            $em->persist($post);
            
            $em->flush();
            return $this->redirectToRoute("forum");
        }
        return $this->render('home/forum.html.twig', [
            'posts' => $posts,
            'categories' => $categories,
            'products' => $products,
            'client' => $client,
            'user' => $user,
            'total' => $cartService->getTotal(),
            'totalItem' => $cartService->getTotalItem(),
            'formulaire' => $formulaire->createView(),
               
        ]);
    }

    /**
     * @Route("/show{id}", name="show_comment")
     */
    public function showComment($id)
    {
        $posts =  $this->getDoctrine()->getRepository(Comments::class)->findOneBy(['id' => $id]);
        $_posts = $this->getDoctrine()->getRepository(Comments::class)->findBy(['parent' => $id]);
      
        return $this->render('home/showComment.html.twig', [
            'posts' => $posts,
            '_posts' => $_posts,
        ]);
    }

    /**
    * @Route("/contact", name="contact")
    */
    public function contact(Request $request, \Swift_Mailer $mailer): Response
    {
        if($request->getMethod() == 'POST')
        {
            $email = $request->request->get('email');
            $body = $request->request->get('message');
            $_website = $request->request->get('website');
            $message = (new \Swift_Message('Prise de contact'))
            ->setFrom($email)
            ->setTo('sowousmane4811@gmail.com')
            ->setBody($body .  '
Mon website est : ' . $_website . '
Envoyé par : '. $email);
            
    
            $mailer->send($message);
        }

        try{
            return $this->render('home/contact.html.twig', [
               'controller_name' => 'HomeController',
            ]);
        }
        catch(\Exception $e){
            $this->addFlash('danger', $e->getMessage());
        }
    }

   
    
}

ecommerce/templates/home/createComment.html.twig
{% extends 'base.html.twig' %}
{% block body %}   
  <link rel="stylesheet" href="{{ asset('css/forumStyle.css') }}" />
   
  <div  class="text-center _logo shadow p-4 ">
    <strong>
        <a href="{{ path("home") }}" > 
            <span style="color: #ff4d00;">O</span><span style="color: #ff6f00;">n</span><span style="color: #f27d00;">l</span><span style="color: #fa6e02;">i</span><span style="color: #ff8400;">n</span><span style="color: #f5a00c;">e</span><span>S</span><span>h</span><span>o</span><span>p</span>
        </a>
    </strong>
    </div>
  <div class="row commentaire_create " style="margin:0px 50px; margin-top:27px;">
    <h1 class="text-center"> Laissez-nous vos commentaires ou vos questions</h1>
    {{ form(formulaire) }}
     <a href="{{ path("forum") }}" class="btn btn-lg text-right btn-cancel-comment ">Anuller</a>
  </div>


{% endblock %}

ecommerce/templates/home/details.html.twig
{% extends 'base.html.twig' %} {% block body %}

{% include 'home/menu.html.twig' %}
{% include 'home/nav_bar.html.twig' %}
<link rel="stylesheet" href="{{ asset('css/details.css') }}" />

<div class="row details_first" >
    <div class=" row retour">
        <a href="{{ path("home") }}">← retour </a>
    </div>

    <div class="text-center well" style="margin-bottom:-50px; margin-left:-16px;"> 
        <h1> Détails du produit <strong>{{product.name}} </strong></h1> 
        <h3> N'hesitez pas à voir en bas du produit les commentaires concernant ce produit et les produits similaires</h3>
    </div>
    <div class="row _details">
        <div class="col-sm-8 class_details_product" id="class_details_product_id">
            <img id="product_image_div" src="{{ asset("images/products/" ~ product.image ~ ".PNG" ) }}" alt="Avatar"
                />
            <h2> Caractéristiques produit</h2>
            <p>
                Eco-Score L'Eco-score vous indique l’impact sur l'environnement des produits alimentaires. Il a été
                élaboré pour favoriser une alimentation plus durable.<br>
                La méthode de calcul estime l’impact de chaque étape de la vie d’un produit
                (production, transport, vente en magasin, cuisine, recyclage des emballages) sur la pollution de
                l'environnement.<br>
                Elle prend notamment en compte :</p>
            <pre> -le mode de production</pre>
            <pre> -le transport</pre>
            <pre> -l’origine géographique des ingrédients</pre>
            <pre> -la recyclabilité de l’emballage</pre>
            <pre> -l’impact sur les espèces menacées </pre>
            <p> Sources des calculs de l'Eco-score: Les scores des produits de marque Carrefour sont calculés par Conso
                Trust.<br>
                Les scores des marques nationales sont calculés par Open Food Facts et consultables
                sur " <a href="https://openfoodfacts.org">https://openfoodfacts.org</a>".<br> Certains scores sont gris,
                en raison du manque d'informations nécessaires, il n'est pas possible de calculer l'Eco-score de ces
                produits.


            </p>
            <hr>
            <h2>Vous pourriez aussi aimer</h2>
            <div class="row">
                <ul class='row articles'>
                    {% for _product in products %}
                    <div class="col-md-4">
                        <li>
                            <div class="cardi">

                                <a href="{{ path("details", {id: _product.id}) }}">

                                    <img src="{{ asset("images/products/" ~ _product.image ~ ".PNG" ) }}" alt="Avatar"
                                        style="width:100%" />
                                    <div class="foot_article">
                                        <h3>{{ product.name }}</h3>
                                        <h4>{{ product.description [:30] }} ...</h4>
                                        <h2> {{ product.price }} €</h2>
                                    </div>
                                </a>

                                <div class="btn-add  text-center">
                                    <a href="{{ path("cart_add", {'id': product.id}) }}" class="btn ">
                                        <span class="fa fa-plus"></span>
                                        <strong>ajouter</strong>
                                    </a>

                                </div>
                            </div>
                        </li>
                    </div>
                    {% endfor %}
                </ul>
            </div>
        </div>
        <div class="col-sm-4 details_div" id="div_to_show_id">
            <div class="details_article">
                <h3>{{ product.name }}</h3>
                <h4>{{ product.description}}</h4>
                <h2> {{ product.price }} €</h2>
                <a href="{{ path("cart_add", {'id': product.id}) }}" class="btn buy_btn">
                    <button type="submit" class="btn " data-toggle="tooltip" data-placement="top"
                        title="Ajouter ce produit dans votre panier">
                        <strong>Acheter</strong>
                        <img class="" src="{{ asset("images/shopping-cart.png") }}" alt="chariot!"
                            style="width:50px; height:50px;" />

                    </button>
                </a>
                
            </div>
            <div class="bottom_details row">
                <a href="{{ path("products_by_category", {id: product.category.id}) }}" class="btn ">
                    <button type="submit" class="btn " data-toggle="tooltip" data-placement="top"
                        title="Retourner sur la page d'accueil">
                        <div class="col-sm-9">
                            <strong>VOIR TOUS LES PRODUITS DU RAYON </strong>
                            <span></span>
                            <img class="details_pic" src="{{ asset("images/carotte.jpg") }}" alt="carotte!"
                                style="width:50px; height:50px;" />

                        </div>
                        <div class="col-sm-3 test">
                            <strong> > </strong>
                        </div>
                    </button>
                </a>
            </div>
        </div>
    </div>
</div>
 <div class="container-fluid commentaire_details_product" style="margin-bottom:150px;">
    <h1 class="text-center"> Discussion sur ce produit</h1>
    <hr>
    {% if comments | length > 0 %}
       {% for post in comments %}
          {% if post.parent == null %}
             <div class="row">
              
              <h3> 
                <strong>{{ post.title }} </strong>
                <a href="#commentaire_create_id_forum" data-reply data-id="{{ post.id }}" class="btn new_post_btn pull-right" style="margin:10px;">
                  Répondre
                </a> 
              </h3>
              <p> publié par 
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-person-fill" viewBox="0 0 16 16">
                <path d="M3 14s-1 0-1-1 1-4 6-4 6 3 6 4-1 1-1 1H3zm5-6a3 3 0 1 0 0-6 3 3 0 0 0 0 6z"/>
              </svg>
              <strong style="  background-color: rgb(221, 213, 202);">{{ post.nickname  }} </strong>le {{ post.createdAt |date('d/m/Y à H:i') }} ce post est: &nbsp; {% if post.active %}actif{% else %}fermé{% endif %}</p>
              <div>
                <a class="link-to-details-post" href="{{ path("show_comment", {'id': post.id}) }}">
                  {{ post.content [:100] }} <span style="color:rgb(11, 114, 161);">voir plus</span>
                </a>
              </div>
            </div> 
            {% for reply in post.replies %}
              <div style="margin-left:50px; background-color: rgb(221, 213, 202);">
                <p> Répondu  par 
                  <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-person-fill" viewBox="0 0 16 16">
                  <path d="M3 14s-1 0-1-1 1-4 6-4 6 3 6 4-1 1-1 1H3zm5-6a3 3 0 1 0 0-6 3 3 0 0 0 0 6z"/>
                </svg>
                <strong style="  background-color: rgb(221, 213, 202);">{{ reply.nickname  }} </strong>le {{ reply.createdAt |date('d/m/Y à H:i') }}</p>
                <div>
                  <a class="link-to-details-post" href="{{ path("show_comment", {'id': reply.id}) }}">
                    {{ reply.content [:100] }} 
                  </a>
                </div>
              </div>
            {% endfor %}
                <hr>
          {% endif %}
        {% endfor %}

    {% else %}
        <div colspan="10" style="background-color:rgb(253, 147, 128);"><h1 > Aucun commentaire sur ce produit</h1></div>
    
    {% endif %}
    
</div>
    <div class="container-fluid commentaire_create " id="commentaire_create_id_forum" style=" margin-top:27px;">
        <h1 class="text-center"> Laissez-nous vos commentaires ou vos questions</h1>
        {{ form(formulaire) }}
    </div>

<script>
    $(document).ready(function () {
        $('[data-toggle="tooltip"]').tooltip();
    });
    var second_div_right = document.getElementById("class_details_product_id");
    var foot__ = second_div_right.scrollHeight - second_div_right.scrollTop; //hauter du des produits
    var Y = foot__ - 600; // position du scroll
    //console.log(" y =  " + Y);
    $(window).scroll(function () {
        //console.log("scrollY   " + window.scrollY)
        if (window.scrollY > Y) {
            $('#div_to_show_id').addClass("class_to_fix");
        } else {
            $('#div_to_show_id').removeClass("class_to_fix");
        }
    });
 
 
    window.onload = () => {
        //on ecoute l'evenement sur tous les bouttons repondre
        document.querySelectorAll("[data-reply]").forEach(element => {
            element.addEventListener("click", function(){
                //console.log(this);
                document.querySelector("#comments_form_parent").value = this.dataset.id;
            })
        })
    } 
</script>


{% endblock %}

ecommerce/templates/home/forum.html.twig
{% extends 'base.html.twig' %}
{% block body %}   
  <link rel="stylesheet" href="{{ asset('css/forumStyle.css') }}" />
    {% include 'home/menu.html.twig' %}
  <div class="row commentaire_ " style="margin:0px 50px; margin-top:217px;">
    <div class="btn-add-comment  text-center row">
      <div class="col-sm-10 text-center  welcome-to-soth " style="margin-bottom:50px;">
       
        Bienvenu au forum  
        <strong class="bg-white" style=" border-radius: 20px; padding:10px">  
          {% if client is defined and client != null %}
            {{ client.firstname }}
          {% else %}
            visiteur
          {% endif %}
        </strong>   
      </div>
      <div class="col-sm-2">
        <a href="#commentaire_create_forum_id" class="btn new_post_btn pulse ">
            <span class="fa fa-plus"></span>
            <strong>Crée un nouveau sujet</strong>
        </a>
      </div> 
    </div>
     <div class="container-fluid commentaire_details">
        {% for post in posts %}
          {% if post.parent == null %}
            <div class="row">
              
              <h3> 
                <strong>{{ post.title }} </strong>
                <a href="#commentaire_create_forum_id" data-reply data-id="{{ post.id }}" class="btn new_post_btn pull-right" style="margin:10px;">
                  Répondre
                </a> 
              </h3>
              <p> publié par 
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-person-fill" viewBox="0 0 16 16">
                <path d="M3 14s-1 0-1-1 1-4 6-4 6 3 6 4-1 1-1 1H3zm5-6a3 3 0 1 0 0-6 3 3 0 0 0 0 6z"/>
              </svg>
              <strong style="  background-color: rgb(221, 213, 202);">{{ post.nickname  }} </strong>le {{ post.createdAt |date('d/m/Y à H:i') }} ce post est: &nbsp; {% if post.active %}actif{% else %}fermé{% endif %}</p>
              <div>
                <a class="link-to-details-post" href="{{ path("show_comment", {'id': post.id}) }}">
                  {{ post.content [:100] }} <span style="color:rgb(11, 114, 161);">voir plus</span>
                </a>
              </div>
            </div>
            {% for reply in post.replies %}
              <div style="margin-left:50px; background-color: rgb(221, 213, 202);">
                <p> Répondu  par 
                  <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-person-fill" viewBox="0 0 16 16">
                  <path d="M3 14s-1 0-1-1 1-4 6-4 6 3 6 4-1 1-1 1H3zm5-6a3 3 0 1 0 0-6 3 3 0 0 0 0 6z"/>
                </svg>
                <strong style="  background-color: rgb(221, 213, 202);"> {{ reply.nickname  }} </strong>le {{ reply.createdAt |date('d/m/Y à H:i') }}</p>
                <div>
                  <a class="link-to-details-post" href="{{ path("show_comment", {'id': reply.id}) }}">
                    {{ reply.content [:100] }} 
                  </a>
                </div>
              </div>
            {% endfor %}
                <hr>
          {% endif %}
        {% endfor %}
        
      </div> 
      
      <div id="commentaire_create_forum_id" class=" container-fluid commentaire_create_forum " >
          <h1 class="text-center"> Laissez-nous vos commentaires ou vos questions</h1>
          {{ form(formulaire) }}
          <a href="{{ path("forum") }}" class="btn btn-lg text-right btn-cancel-comment ">Anuller</a>
      </div>
  </div>


<script>
  window.onload = () =>{
    //on met un écouter sur l'evenment des button
    document.querySelectorAll("[data-reply]").forEach(element =>{
      element.addEventListener("click", function(){
        document.querySelector("#comments_form_parent").value = this.dataset.id;
      });
    });
    
  }
</script>


{% endblock %}

ecommerce/templates/home/home.html.twig
{% extends 'base.html.twig' %}
{% block body %}
    {% include 'home/menu.html.twig' %}
    {% include 'home/nav_bar.html.twig' %}
    <div class="row" style="margin-top:217px; margin-bottom:20px;  background-color: rgb(238, 238, 238);">
    <div class="col-md-3 firstd" id="firstd_id">
        {% include 'home/sidebar.html.twig' %}
    </div>
    <div class="col-md-9 firstdo" id="firstdo_id">
        <ul class='row articles'>
            {% for product in products %}
                <div class="col-md-3">
                    <li>
                        <div class="cardi">
                            <a href="{{ path("details", {'id': product.id}) }}">
                                <img src="{{ asset("images/products/" ~ product.image ~ ".PNG") }}" alt="Avatar" style="width:100%" />
                                <div class="foot_article">
                                    <h3>{{ product.name }}</h3>                                   
                                    <h4>{{  product.description [:20] }} ...</h4>
                                    <h2> {{ product.price }} €</h2>
                                </div>
                            </a>

                            <div class="btn-add text-center">
                                <a href="{{ path("cart_add", {'id': product.id}) }}" class="btn ">
                                    <span class="fa fa-plus"></span>
                                    <strong>ajouter</strong>
                                </a>
                            </div>
                        </div>
                    </li>
                </div>
            {% endfor %}
        </ul>
    </div>


</div>

    <script>
        var second_div_right = document.getElementById("firstdo_id");
        var foot__ = second_div_right.scrollHeight - second_div_right.scrollTop ; //hauter du des produits
        var Y = foot__ -1000; // position du scroll
        console.log(" y =  " + Y);
        $(window).scroll(function () {
            console.log("scrollY   " + window.scrollY)
            if (window.scrollY > Y) {
                 $('#firstd_id').addClass("sticky");
                 $('#firstdo_id').addClass("resize_div");
            } else {
             $('#firstd_id').removeClass("sticky");
                 $('#firstdo_id').removeClass("resize_div");
            }
            
        });
    </script>
{% endblock %}

ecommerce/templates/home/productsByCategory.html.twig
{% extends 'base.html.twig' %}
{% block body %}
    {% include 'home/menu.html.twig' %}
    {% include 'home/nav_bar.html.twig' %}
    <div class="row" style="margin-top:217px; margin-bottom:20px;">
    <div class="col-md-3 firstd" id="firstd_id">
        {% include 'home/sidebar.html.twig' %}
    </div>
    <div class="col-md-9 firstdo" id="firstdo_id">
        <ul class='row articles'>
            {% for product in products %}
                <div class="col-md-3">
                    <li>
                        <div class="cardi">
                            <a href="{{ path("details", {id: product.id}) }}">
                                <img src="{{ asset("images/products/" ~ product.image ~ ".PNG") }}" alt="Avatar" style="width:100%" />
                                <div class="foot_article">
                                    <h2>Asperges blanches ou violettes</h2>
                                    <h5>la botte de 500g</h5>
                                    <h5>5€ /kilogramme</h5>
                                    <h3>{{ product.name }}</h2>
                                        <h2> {{ product.price }} €</h2>
                                </div>
                            </a>

                            <div class="btn-add  text-center">
                                <button type="submit" class="btn ">
                                    <span class="fa fa-plus"></span>
                                    <strong>ajouter</strong>
                                </button>
                                

                            </div>
                        </div>
                    </li>
                </div>
            {% endfor %}
        </ul>
    </div>


</div>
{% endblock %}

ecommerce/templates/home/showComment.html.twig
{% extends 'base.html.twig' %}
{% block body %}
<link rel="stylesheet" href="{{ asset('css/forumStyle.css') }}" />
<div class="well">
    <div class=" row retour">
        <a href="{{ path("forum") }}">
            < retour aux forum </a>
    </div>
    <div class="text-center _logo   ">
        <strong>
            <a href="{{ path("home") }}">
                <span style="color: #ff4d00;">O</span><span style="color: #ff6f00;">n</span><span
                    style="color: #f27d00;">l</span><span style="color: #fa6e02;">i</span><span
                    style="color: #ff8400;">n</span><span
                    style="color: #f5a00c;">e</span><span>S</span><span>h</span><span>o</span><span>p</span>
            </a>
        </strong>
    </div>
</div>
<div class="row commentaire_details_s  container" style="margin:50px 40%;">
  <h1 style="margin-bottom:50px; ">Ceci est un detail du commentaire  </h1>

    <h3> <strong> <i>{{ posts.title }} </i></strong></h3>
        
      </h3>
      <p> publié par 
        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-person-fill" viewBox="0 0 16 16">
        <path d="M3 14s-1 0-1-1 1-4 6-4 6 3 6 4-1 1-1 1H3zm5-6a3 3 0 1 0 0-6 3 3 0 0 0 0 6z"/>
      </svg>
      <strong style="  background-color: rgb(221, 213, 202);"> {{ posts.nickname  }} </strong> le {{ posts.createdAt |date('d/m/Y à H:i') }} ce post est: &nbsp; {% if posts.active %}actif{% else %}fermé{% endif %}</p>
      <div>
          {{ posts.content }} 
      </div>
      <h1 class=" text-success"> Réponses:</h1>
  {% for comment in _posts %}
      <p> Répondu par 
        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-person-fill" viewBox="0 0 16 16">
        <path d="M3 14s-1 0-1-1 1-4 6-4 6 3 6 4-1 1-1 1H3zm5-6a3 3 0 1 0 0-6 3 3 0 0 0 0 6z"/>
      </svg>
      <strong style="  background-color: rgb(221, 213, 202);">{{ comment.nickname  }}</strong> le {{ comment.createdAt |date('d/m/Y à H:i') }} ce post est: &nbsp; {% if comment.active %}actif{% else %}fermé{% endif %}</p>
      <div>
          {{ comment.content }} 
      </div>
  {% endfor %}
</div>  


{% endblock %}